apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtualmachine.fullname" . }}
  labels:
    {{- include "virtualmachine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ toYaml .Values.service.ports | nindent 2 }}
  selector:
    vm.kubevirt.io/name: {{ include "virtualmachine.fullname" . }}